### ISSUE TITLE
Zorg ervoor dat je Library en andere folders niet mee gepushed worden naar git.

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#1]
Je hebt feedback gekregen van **SilvanDomino**
op:

``` c
￿ 
```

URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Library/AnnotationManager

Feedback: Je hebt je .gitignore verkeerd ingesteld dus dan wordt de library en temp folders mee geupload naar git. Zorg dat de eerste regels in .gitignore naar de juist folders wijzen.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
This should be fixed now
