### ISSUE TITLE
Kort

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#11]
Je hebt feedback gekregen van **SilvanDomino**
URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Assets/_Scripts/ReloadScript.cs

Feedback: Deze script is extreem kort. Is dat nodig? Ook de naamgeving is dubbel op. Het is duidelijk een script, niet nodig om erbij te zeggen dat het een script is.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
Script naming verandered naar ReloadScene.
