### ISSUE TITLE
Te veel scripts in een map.

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#2]
Je hebt feedback gekregen van **SilvanDomino**
URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Assets/_Scripts

Feedback: Er zijn te veel scripts in een map. Probeer meer mappen aan te maken om je scripts te sorteren.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
Scrips zijn nu gesorteerd in 2 mappen
