### ISSUE TITLE
Naamgeving

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#3]
Je hebt feedback gekregen van **SilvanDomino**
URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Assets/_Scripts/BulletController.cs

Feedback: De naam bulletcontroller is totaal niet duidelijk. Als ik dit lees heb ik totaal geen idee wat het doet.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
Naming is nu verandert naar BulletBehavior
