### ISSUE TITLE
Overbodig

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#5]
Je hebt feedback gekregen van **SilvanDomino**
op:

``` c
IEnumerator lifetime(){
        yield return new WaitForSeconds(7f);
        Destroy(gameObject);
    } 
```

URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Assets/_Scripts/BulletController.cs

Feedback: Destroy kan je een float meegeven die die de destroy een timer meegeeft. Die gebruiken is een stuk makkelijker een logischer dan een coroutine gebruiken.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
Is nu in de start gezet met de juiste timing
