### ISSUE TITLE
Te hard gekoppeled met CanDropBomb

### ISSUE THREAD

**Issue by SilvanDomino** [tommtom9/week1-WormsCollision#6]
Je hebt feedback gekregen van **SilvanDomino**
URL: https://github.com/tommtom9/week1-WormsCollision/blob/master/Worms terrain/Assets/_Scripts/SpawnBulletAtMouse.cs

Feedback: Deze class is _extreem_ hard gekoppeled met CanDropBomb. Je zou deze los moeten koppelen of in een class moeten doen.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by tommtom9** [comment]
Nu meer los gekopeld
